server:
  port: 8081

spring:
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://127.0.0.1:5432/db_yfinance"
    username: "postgres"
    password: "88888888"
    # driverClassName: "com.mysql.jdbc.Driver"
    # url: "jdbc:mysql://127.0.0.1:3306/BOOTCAMP_2408"
    # username: "root"
    # password: "88888888"
  jpa:
    show-sql: true # this line shows the SQL executed in the terminal
    hibernate.ddl-auto: create

# Custom variables
api:
  yf:
    domain: "query1.finance.yahoo.com"
    endpoints: "/v7/finance/quote"

